<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>AlterCourse.AssetCtl</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="JsonSchema.Net" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="SkiaSharp" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
		<PackageReference Include="Svg.Skia" />
		<PackageReference Include="YamlDotNet" />
	</ItemGroup>
</Project>
